# -*- coding: utf-8 -*-
"""
/***************************************************************************
 serg
                                 A QGIS plugin
 qgis_pno
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-12-13
        copyright            : (C) 2021 by serg
        email                : serg
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load serg class from file serg.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pno import serg
    return serg(iface)
